import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import "./main.scss";
import Footer from "@/components/footer/footer";
import CustomNav from "@/components/navbar/navbar";

const dm = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdn.jsdelivr.net/npm/flowbite@2.4.1/dist/flowbite.min.css"
          rel="stylesheet"
        />
      </head>
      <body className={dm.className}>
        <CustomNav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
