import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import "./main.scss";
import Navbar from "@/components/navbar";

const dm = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={dm.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
